# Práctica de RM

### Importamos las librerías básicas y para ajustes

In [5]:
import numpy as np

from numpy.linalg import *

import scipy.optimize as so

import matplotlib.pyplot as plt

%matplotlib inline

from IPython.display import display, Latex

import pandas as pd
pd.set_option('precision', 2)

from openpyxl import load_workbook
wb = load_workbook(filename='openpyxl.xlsx', read_only=True)

In [6]:
def media(xlist):
    return sum(xlist)/len(xlist)

def sigma(xlist):
    return np.sqrt(sum((xlist-media(xlist))**2)/(1.*len(xlist)*(len(xlist)-1.)))

def sigmab(xlist):
    return np.sqrt(sum((xlist-media(xlist))**2)/(1.*len(xlist)*(len(xlist)-1)))

def utotal(ua,ub):
    return np.sqrt(ua**2+ub**2)

#ajuste lineal y=a+bx
def ajustelinealponderado(x,y,sig):

    H=np.array([[sum(1./sig**2),sum(x/sig**2)],[sum(x/sig**2),sum(x**2/sig**2)]])
    Delta=det(H)
    w=1.0/(sig*sig)
    Z=np.array([sum(y/sig**2),sum((x*y)/sig**2)])
    
    ([a,b])=np.matmul(inv(H),Z)
    
    siga=np.sqrt(sum(x**2/sig**2)/Delta)
    sigb=np.sqrt(sum(1./sig**2)/Delta)
    r=(sum(w) * sum(w*x*y) - sum(w*x) * sum(w*y))/(np.sqrt ((sum(w) * sum(w*x*x) - sum(w*x) **2 )*( sum(w) * sum(w*y*y) - sum(w*y) **2)))
    
    return a,b,siga,sigb,r


## Distancia = 211

### De aquí importamos los datos que necesitamos para el ajuste

In [7]:
ws = wb['Hoja1']
x1=np.array([])
x2=np.array([])
for i in range(5):#añado B a x1
    x1=np.append(x1,[ws.cell(row=i+2,column=2).value])
for i in range(5):#añado C a x2
    x2=np.append(x2,[ws.cell(row=i+2,column=3).value])
delta=0.0005



In [8]:
print (x1,x2,delta)

[ 4.014  4.012  4.023  4.015  4.018] [ 0.058  0.058  0.058  0.058  0.058] 0.0005


In [9]:
x1t=media(x1)
x2t=media(x2)
ua1=sigmab(x1)
ua2=sigmab(x2)
ub=0.0005
ux1=utotal(ua1,ub)
ux2=utotal(ua2,ub)
print (x1t,ux1)
print (x2t,ux2)

4.0164 0.00197737199333
0.058 0.0005


## Distancia = 391

### De aquí importamos los datos que necesitamos para el ajuste

In [10]:
ws = wb['Hoja1']
x1=np.array([])
x2=np.array([])
for i in range(5):#añado B a x1
    x1=np.append(x1,[ws.cell(row=i+2,column=5).value])
for i in range(5):#añado C a x2
    x2=np.append(x2,[ws.cell(row=i+2,column=6).value])
delta=0.0005



In [11]:
print (x1,x2,delta)

[ 5.486  5.486  5.489  5.494  5.505] [ 0.043  0.043  0.044  0.043  0.043] 0.0005


In [12]:
x1t=media(x1)
x2t=media(x2)
ua1=sigmab(x1)
ua2=sigmab(x2)
ub=0.0005
ux1=utotal(ua1,ub)
ux2=utotal(ua2,ub)
print (x1t,ux1)
print (x2t,ux2)

5.492 0.00359861084309
0.0432 0.000538516480713


## Distancia = 171

### De aquí importamos los datos que necesitamos para el ajuste

In [13]:
ws = wb['Hoja1']
x1=np.array([])
x2=np.array([])
for i in range(5):#añado B a x1
    x1=np.append(x1,[ws.cell(row=i+2,column=8).value])
for i in range(5):#añado C a x2
    x2=np.append(x2,[ws.cell(row=i+2,column=9).value])
delta=0.0005



In [14]:
print (x1,x2,delta)

[ 3.629  3.631  3.634  3.645  3.632] [ 0.064  0.064  0.064  0.064  0.064] 0.0005


In [15]:
x1t=media(x1)
x2t=media(x2)
ua1=sigmab(x1)
ua2=sigmab(x2)
ub=0.0005
ux1=utotal(ua1,ub)
ux2=utotal(ua2,ub)
print (x1t,ux1)
print (x2t,ux2)

3.6342 0.00286181760425
0.064 0.0005


## Distancia = 274

### De aquí importamos los datos que necesitamos para el ajuste

In [16]:
ws = wb['Hoja1']
x1=np.array([])
x2=np.array([])
for i in range(5):#añado B a x1
    x1=np.append(x1,[ws.cell(row=i+2,column=11).value])
for i in range(3):#añado C a x2
    x2=np.append(x2,[ws.cell(row=i+2,column=12).value])
delta=0.0005



In [17]:
print (x1,x2,delta)

[ 4.586  4.577  4.577  4.587  4.574] [ 0.052  0.052  0.052] 0.0005


In [18]:
x1t=media(x1)
x2t=media(x2)
ua1=sigmab(x1)
ua2=sigmab(x2)
ub=0.0005
ux1=utotal(ua1,ub)
ux2=utotal(ua2,ub)
print (x1t,ux1)
print (x2t,ux2)

4.5802 0.00268141753556
0.052 0.0005


## Distancia = 326

### De aquí importamos los datos que necesitamos para el ajuste

In [19]:
ws = wb['Hoja1']
x1=np.array([])
x2=np.array([])
for i in range(5):#añado B a x1
    x1=np.append(x1,[ws.cell(row=i+2,column=14).value])
for i in range(3):#añado C a x2
    x2=np.append(x2,[ws.cell(row=i+2,column=15).value])
delta=0.0005



In [20]:
print (x1,x2,delta)

[ 4.985  4.999  4.983  4.984  4.984] [ 0.047  0.048  0.048] 0.0005


In [21]:
x1t=media(x1)
x2t=media(x2)
ua1=sigmab(x1)
ua2=sigmab(x2)
ub=0.0005
ux1=utotal(ua1,ub)
ux2=utotal(ua2,ub)
print (x1t,ux1)
print (x2t,ux2)

4.987 0.00305777697028
0.0476666666667 0.000600925212577


## Distancia =  442

### De aquí importamos los datos que necesitamos para el ajuste

In [22]:
ws = wb['Hoja1']
x1=np.array([])
x2=np.array([])
for i in range(5):#añado B a x1
    x1=np.append(x1,[ws.cell(row=i+2,column=17).value])
for i in range(3):#añado C a x2
    x2=np.append(x2,[ws.cell(row=i+2,column=18).value])
delta=0.0005



In [23]:
print (x1,x2,delta)

[ 5.805  5.827  5.797  5.796  5.799] [ 0.039  0.039  0.039] 0.0005


In [24]:
x1t=media(x1)
x2t=media(x2)
ua1=sigmab(x1)
ua2=sigmab(x2)
ub=0.0005
ux1=utotal(ua1,ub)
ux2=utotal(ua2,ub)
print (x1t,ux1)
print (x2t,ux2)

5.8048 0.00578705451849
0.039 0.0005


## Distancia =  515

### De aquí importamos los datos que necesitamos para el ajuste

In [25]:
ws = wb['Hoja1']
x1=np.array([])
x2=np.array([])
for i in range(5):#añado B a x1
    x1=np.append(x1,[ws.cell(row=i+2,column=20).value])
for i in range(3):#añado C a x2
    x2=np.append(x2,[ws.cell(row=i+2,column=21).value])
delta=0.0005



In [26]:
print(x1,x2,delta)

[ 6.262  6.169  6.266  6.276  6.27 ] [ 0.037  0.037  0.037] 0.0005


In [27]:
x1t=media(x1)
x2t=media(x2)
ua1=sigmab(x1)
ua2=sigmab(x2)
ub=0.0005
ux1=utotal(ua1,ub)
ux2=utotal(ua2,ub)
print (x1t,ux1)
print (x2t,ux2)

6.2486 0.0200402095797
0.037 0.0005


## Distancia =  581

### De aquí importamos los datos que necesitamos para el ajuste

In [28]:
ws = wb['Hoja1']
x1=np.array([])
x2=np.array([])
for i in range(5):#añado B a x1
    x1=np.append(x1,[ws.cell(row=i+2,column=23).value])
for i in range(3):#añado C a x2
    x2=np.append(x2,[ws.cell(row=i+2,column=24).value])
delta=0.0005



In [29]:
print (x1,x2,delta)

[ 6.663  6.654  6.663  6.661  6.651] [ 0.035  0.033  0.033] 0.0005


In [30]:
x1t=media(x1)
x2t=media(x2)
ua1=sigmab(x1)
ua2=sigmab(x2)
ub=0.0005
ux1=utotal(ua1,ub)
ux2=utotal(ua2,ub)
print (x1t,ux1)
print (x2t,ux2)

6.6584 0.00253179778023
0.0336666666667 0.000833333333333


## Distancia =  129

### De aquí importamos los datos que necesitamos para el ajuste

In [31]:
ws = wb['Hoja1']
x1=np.array([])
x2=np.array([])
for i in range(5):#añado B a x1
    x1=np.append(x1,[ws.cell(row=i+2,column=26).value])
for i in range(3):#añado C a x2
    x2=np.append(x2,[ws.cell(row=i+2,column=27).value])
delta=0.0005



In [32]:
print (x1,x2,delta)

[ 3.171  3.174  3.159  3.16   3.158] [ 0.072  0.072  0.072] 0.0005


In [33]:
x1t=media(x1)
x2t=media(x2)
ua1=sigmab(x1)
ua2=sigmab(x2)
ub=0.0005
ux1=utotal(ua1,ub)
ux2=utotal(ua2,ub)
print (x1t,ux1)
print (x2t,ux2)

3.1644 0.00339263909074
0.072 0.0005


## Distancia =  369

### De aquí importamos los datos que necesitamos para el ajuste

In [34]:
ws = wb['Hoja1']
x1=np.array([])
x2=np.array([])
for i in range(5):#añado B a x1
    x1=np.append(x1,[ws.cell(row=i+2,column=29).value])
for i in range(3):#añado C a x2
    x2=np.append(x2,[ws.cell(row=i+2,column=30).value])
delta=0.0005



In [35]:
print (x1,x2,delta)

[ 5.311  5.301  5.303  5.307  5.308] [ 0.043  0.043  0.043] 0.0005


In [36]:
x1t=media(x1)
x2t=media(x2)
ua1=sigmab(x1)
ua2=sigmab(x2)
ub=0.0005
ux1=utotal(ua1,ub)
ux2=utotal(ua2,ub)
print (x1t,ux1)
print (x2t,ux2)

5.306 0.0018574175621
0.043 0.0005
